import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';

import { LanguageProvider } from "./contexts/LanguageContext";
import RootLayoutClient from "./RootLayoutClient";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-tajawal !bg-white">
        <LanguageProvider>
          <RootLayoutClient>{children}</RootLayoutClient>
        </LanguageProvider>
      </body>
    </html>
  );
}
